export const INVOICE_TYPOGRAPHY_ADJUSTMENT_PX = 2;

const adjusted = (basePx: number) => basePx + INVOICE_TYPOGRAPHY_ADJUSTMENT_PX;

export const INVOICE_TYPOGRAPHY = {
    ui: {
        brandPx: adjusted(36),
        brandMetaPx: adjusted(12),
        documentTitlePx: adjusted(20),
        documentNumberPx: adjusted(36),
        sectionLabelPx: adjusted(10),
        customerHeadingPx: adjusted(18),
        customerLinePx: adjusted(12),
        customerIdPx: adjusted(10),
        metaRowPx: adjusted(12),
        itemHeaderPx: adjusted(10),
        detailPx: adjusted(14),
        itemColorPx: adjusted(10),
        totalPcsPx: adjusted(16),
        totalLabelPx: adjusted(10),
        bankTitlePx: adjusted(10),
        bankCopyPx: adjusted(10),
        legalPx: adjusted(9),
        summaryLabelPx: adjusted(12),
        summaryValuePx: adjusted(16),
        grandTotalLabelPx: adjusted(18),
        currencyPx: adjusted(10),
        grandTotalAmountPx: adjusted(30),
        socialPx: adjusted(10),
        thanksPx: adjusted(11),
    },
    pdf: {
        brandPx: adjusted(23),
        brandMetaPx: adjusted(7.5),
        documentTitlePx: adjusted(13),
        documentNumberPx: adjusted(25),
        sectionLabelPx: adjusted(8),
        customerNamePx: adjusted(12),
        customerLinePx: adjusted(8),
        metaRowPx: adjusted(8),
        itemHeaderPx: adjusted(7.2),
        itemDetailPx: adjusted(8.4),
        itemColorPx: adjusted(7.2),
        totalPcsPx: adjusted(11),
        totalLabelPx: adjusted(7),
        bankTitlePx: adjusted(7.3),
        bankCopyPx: adjusted(6.6),
        summaryRowPx: adjusted(8),
        grandTotalLabelPx: adjusted(11),
        grandTotalAmountPx: adjusted(24),
        currencyPx: adjusted(7),
        legalPx: adjusted(5.8),
        socialPx: adjusted(6.4),
        thanksPx: adjusted(7.5),
    },
} as const;
