begin;

create table if not exists public.shipment_status_change_log (
  id bigint generated by default as identity primary key,
  operation_id uuid not null,
  shipment_id integer not null,
  shipment_number integer not null,
  actor_user_id text,
  actor_name text,
  selected_date date not null,
  from_status text not null,
  to_status text not null,
  event_type text not null check (
    event_type in (
      'STARTED',
      'SHEETS_UPDATED',
      'SYSTEM_UPDATED',
      'COMPLETED',
      'FAILED',
      'ROLLED_BACK',
      'ROLLBACK_FAILED'
    )
  ),
  details jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists shipment_status_change_log_operation_idx
  on public.shipment_status_change_log (operation_id, created_at);

create index if not exists shipment_status_change_log_shipment_idx
  on public.shipment_status_change_log (shipment_number, created_at desc);

alter table public.shipment_status_change_log enable row level security;

revoke all on table public.shipment_status_change_log from anon, authenticated;
revoke all on sequence public.shipment_status_change_log_id_seq from anon, authenticated;

lock table public."Shipment" in share row exclusive mode;

do $$
declare
  repair_operation_id uuid := gen_random_uuid();
begin
  insert into public.shipment_status_change_log (
    operation_id,
    shipment_id,
    shipment_number,
    actor_name,
    selected_date,
    from_status,
    to_status,
    event_type,
    details
  )
  select
    repair_operation_id,
    shipment.id,
    shipment.shipment_number,
    'Migracion de integridad',
    current_date,
    'COMPRAR',
    'SIN ESTADO',
    'SYSTEM_UPDATED',
    jsonb_build_object(
      'reason', 'COMPRAR pertenece a pedidos y no es un estado valido de envio.',
      'repair', '20260804193000_forbid_comprar_shipment_status'
    )
  from public."Shipment" shipment
  where upper(btrim(coalesce(shipment.status, ''))) = 'COMPRAR'
    and shipment.shipment_number is not null;

  update public."Shipment"
  set status = null
  where upper(btrim(coalesce(status, ''))) = 'COMPRAR';
end;
$$;

alter table public."Shipment"
  drop constraint if exists shipment_status_not_comprar;

alter table public."Shipment"
  add constraint shipment_status_not_comprar
  check (status is null or upper(btrim(status)) <> 'COMPRAR');

comment on constraint shipment_status_not_comprar on public."Shipment" is
  'Prevents the order-only COMPRAR status from being stored on shipments.';

commit;
