create table if not exists public.shipment_status_change_log (
  id bigint generated by default as identity primary key,
  operation_id uuid not null,
  shipment_id integer not null,
  shipment_number integer not null,
  actor_user_id text,
  actor_name text,
  selected_date date not null,
  from_status text not null,
  to_status text not null,
  event_type text not null check (
    event_type in (
      'STARTED',
      'SHEETS_UPDATED',
      'SYSTEM_UPDATED',
      'COMPLETED',
      'FAILED',
      'ROLLED_BACK',
      'ROLLBACK_FAILED'
    )
  ),
  details jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists shipment_status_change_log_operation_idx
  on public.shipment_status_change_log (operation_id, created_at);

create index if not exists shipment_status_change_log_shipment_idx
  on public.shipment_status_change_log (shipment_number, created_at desc);

alter table public.shipment_status_change_log enable row level security;

revoke all on table public.shipment_status_change_log from anon, authenticated;
revoke all on sequence public.shipment_status_change_log_id_seq from anon, authenticated;

comment on table public.shipment_status_change_log is
  'Append-only audit trail for IMPORTSYS shipment status transitions and Google Sheets synchronization.';
